apiVersion: v1
kind: ConfigMap
metadata:
  name: php-app-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_NAME: {{ .Values.mysql.database | quote }}
  DB_USER: {{ .Values.mysql.user | quote }}
