apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: {{ .Values.php.replicaCount }}

  selector:
    matchLabels:
      app: php-app

  template:
    metadata:
      labels:
        app: php-app

    spec:
      containers:
        - name: php-app
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}

          ports:
            - containerPort: 80

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: php-app-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: php-app-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: php-app-config
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
